export const sample_foods = [
  {
    id: '1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: '/foods/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'Meatball',
    cookTime: '15-25',
    price: 12,
    favorite: true,
    origins: ['Italy'],
    stars: 4,
    imageUrl: '/foods/food-2.jpg',
    tags: ['Pasta', 'Lunch', 'Dinner'],
  },
  {
    id: '3',
    name: 'Chicken Burger',
    cookTime: '20-30',
    price: 20,
    favorite: false,
    origins: ['Japan'],
    stars: 3,
    imageUrl: '/foods/food-3.jpg',
    tags: ['Seafood', 'Dinner', 'Healthy'],
  },
  {
    id: '4',
    name: 'French Fries',
    cookTime: '5-15',
    price: 8,
    favorite: true,
    origins: ['USA'],
    stars: 3.5,
    imageUrl: '/foods/food-4.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id: '5',
    name: 'Vegetable Salad',
    cookTime: '10-15',
    price: 6,
    favorite: false,
    origins: ['Global'],
    stars: 4,
    imageUrl: '/foods/food-5.jpg',
    tags: ['Healthy', 'Salad', 'Vegan'],
  },
  {
    id: '6',
    name: 'Vegetable Pizza',
    cookTime: '25-35',
    price: 15,
    favorite: true,
    origins: ['India'],
    stars: 5,
    imageUrl: '/foods/food-6.jpg',
    tags: ['Curry', 'Dinner', 'Spicy','Pizza'],
  },
  {
    id: '7',
    name: 'Hyderabadi Veg Biryani',
    cookTime: '35-40',
    price: 18,
    favorite: true,
    origins: ['India'],
    stars: 5,
    imageUrl: `/foods/food-7.jpg`,
    tags: ['Curry', 'Dinner', 'Spicy'],
  },
  {
    id: '8',
    name: 'Lemon Rice',
    cookTime: '25-25',
    price: 12,
    favorite: true,
    origins: ['India'],
    stars: 5,
    imageUrl: '/foods/food-8.jpg',
    tags: ['Dinner'],
  },
];

export const sample_tags = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 2 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'Dinner', count: 6 },
  { name: 'Healthy', count: 2 },
  { name: 'Spicy', count: 2 },
];

export const sample_users =[
  {
    id:1,
    name:'Jahnavi Gorle',
    email:'janu@gmail.com',
    password:'123',
    address:'Toronto On',
    isAdmin:false
  },
  {
    id:2,
    name:'Anu Gorle',
    email:'anu@gmail.com',
    password:'123',
    address:'Shanghai',
    isAdmin:true
  },
];